plugins {
    id 'java'
}

group = 'code.shubham'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

repositories {
    mavenCentral()
    maven {
        url 'https://packages.confluent.io/maven/'
    }
}

dependencies {
    implementation 'org.apache.kafka:connect-api:3.9.0'
    implementation 'org.apache.kafka:kafka-clients:3.9.0'
    implementation 'io.confluent:kafka-avro-serializer:7.8.0'

    implementation 'org.mongodb:mongodb-driver-sync:5.3.0'
    implementation 'org.postgresql:postgresql:42.7.4'

    implementation 'com.google.code.gson:gson:2.11.0'

    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.20.0'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

task buildFatJar(type: Jar) {
    manifest {
        attributes 'Main-Class': 'code.shubham.Main'
    }
    archiveBaseName = 'custom-confluent-kafka-connector'
    archiveVersion = '1.0.0'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    destinationDirectory = file('connect-plugins/jar')
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}